version: '3.8'
services:
  app: 
    container_name: spring-boot-mysql-app
    image: devopswthaws58/spring-boot-mysql-docker-compose
    networks:
      - springboot-db-net
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    volumes:
      - /springboot-app/data
  mysqldb:
    image: mysql:latest
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - ./app:/var/lib/mysql
networks:
  springboot-db-net: