version: '3.8'
services:
  app: 
    image: spring-boot-mysql-app
    networks:
      - springboot-db-net
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    volumes:
      - data:/springboot-app/data
  mysqldb:
    image: mysql:5.9
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - data:/mysql/data
networks:
  springboot-db-net:
volumes:
  data: {}
