version: '3.8'
services:
  app: 
    image: spring-boot-mysql-app
    networks:
      - springboot-db-net
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    volumes:
      - /springboot-app/data
  mysqldb:
    image: mysql:latest
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - data:/var/lib/mysql
networks:
  springboot-db-net:
volumes:
  data: {}