spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cdbkfb3nf9sm.ap-south-1.rds.amazonaws.com:3306/devopsaws
    username: admin
    password: devopsaws
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
